language: node_js
dist: trusty
sudo: false
node_js:
    - "node"
cache:
    directories:
        - "node_modules"

install:
    - gem install slightish
    - npm install
after_success: npm run coverage
