#!/bin/bash

here=`dirname "$0"`
cd "$here"

if ! type slightish >/dev/null; then
    echo 'Please install the slightish test framework:' >&2
    echo '$ [sudo] gem install slightish' >&2
    exit 2
fi

PATH="$(pwd)/bin:$PATH" \
PAGER=cat \
JUTIL_CONFIG_PATH="$(pwd)/fixtures/blank-config" \
SLIGHTISH_TEMPLATE_DIR="$(pwd)/fixtures" \
slightish *.tush.md
