#!/bin/bash

here=`dirname "$0"`
cd "$here"

PATH="$(pwd)/tush/bin:$(pwd)/bin:$PATH" \
TEST_DIR="$(pwd)" \
JUTIL_CONFIG_PATH="$(pwd)/fixtures/blank_config" \
FIXTURE_DIR="$(pwd)/fixtures" \
tush-check -x *.tush.md
